name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build Go project
      run: |
        GOOS=linux GOARCH=amd64 go build -o main main.go
        zip function.zip main

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'ap-southeast-1'
        function_name: 'domytest'
        zip_file: 'function.zip'
        environment: MONGOSTRING=${{ secrets.MONGOSTRING }}
