name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1 # Change to yours
  ENTRY_FILE: main.go # Change to yours
  FUNCTION_NAME: domikacrot # Change to yours
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: install Serverless Framework
        run: doctl serverless install

      - name: Conenct to Namespace
        run: doctl serverless connect

      - name: Deploy Serverless
        run: doctl serverless deploy . --remote-build